const { name, version } = require("../package.json");

const TITLE = `/* eslint-disable */\n/* tslint:disable */\n// Generated by ${name}@${version}\n`;

exports.generateESModule = function generateESModule(links) {
    return TITLE + links.map(l => `export ${l}`).join('\n')
};

exports.generateCommonJSModule = function generateCommonJSModule(links) {
    const names = links.map(l => /function (.*)\(/.exec(l)[1].trim());

    return `${TITLE}"use strict";\n${links.join('\n')}\nmodule.exports = {${names.join(', ')}}`
};
